//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskfor3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableExRate
    {
        public string title { get; set; }
        public System.DateTime pubDate { get; set; }
        public double description { get; set; }
        public int quant { get; set; }
    }
}
